version: '3.7'

networks:
  backend:
    driver: bridge

services:
  workspace:
    tty: true
    build:
      context: ./workspace
      dockerfile: ./Dockerfile
      args:
        APP_USER_ID: '${APP_USER_ID}'
        APP_GROUP_ID: '${APP_GROUP_ID}'
    volumes:
      - ${APP_PATH}:/var/www/html
    networks:
      - backend

  mariadb:
    build:
      context: ./mariadb
      dockerfile: ./Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
    volumes:
      - ${APP_DATA_PATH}/mariadb/var/lib/mysql:/var/lib/mysql:delegated
    networks:
      - backend
